### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by Zeevian** [MoSadie/ExponentialPower#11]
Getting the same crash with and without minecraft flux.

[crash-2017-07-15_18.39.40-client.txt](https://github.com/MoSadie/ExponentialPower/files/1150684/crash-2017-07-15_18.39.40-client.txt)

using forge 1.11.2-13.20.1.2393

**Comment by martindiv** [comment]
This only appears to happen with MC Flux 2.8.0. Downgrading MC FLux to 2.7.1 does not produce this error.

This error also happens on multi-player servers but the error is a little more verbose.

```
Caused by: java.lang.ClassNotFoundException: io.github.mosadie.ExponentialPower.TileEntitys.EnderGeneratorTE
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at io.github.mosadie.ExponentialPower.Blocks.BlockManager.createBlocks(BlockManager.java:14) ~[BlockManager.class:?]
	at io.github.mosadie.ExponentialPower.CommonProxy.preInit(CommonProxy.java:18) ~[CommonProxy.class:?]
	at io.github.mosadie.ExponentialPower.ServerProxy.preInit(ServerProxy.java:10) ~[ServerProxy.class:?]
	at io.github.mosadie.ExponentialPower.ExponentialPower.preInit(ExponentialPower.java:26) ~[ExponentialPower.class:?]
[ rest of stack trace removed ]

Caused by: java.lang.NoClassDefFoundError: szewek/mcflux/api/ex/IEnergy
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_131]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_131]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at io.github.mosadie.ExponentialPower.Blocks.BlockManager.createBlocks(BlockManager.java:14) ~[BlockManager.class:?]
	at io.github.mosadie.ExponentialPower.CommonProxy.preInit(CommonProxy.java:18) ~[CommonProxy.class:?]
	at io.github.mosadie.ExponentialPower.ServerProxy.preInit(ServerProxy.java:10) ~[ServerProxy.class:?]
	at io.github.mosadie.ExponentialPower.ExponentialPower.preInit(ExponentialPower.java:26) ~[ExponentialPower.class:?]
[ rest of stack trace removed ]

```

I hope this helps.

**Comment by MoSadie** [comment]
_facepalms_ I know exactly what happened. I forgot to update the version of MCFlux that I am developing with. There were recent changes to MCFlux that moved the "missing" class. But Curse still suggests the latest version of MCFlux for playing with. Should be a decently quick fix. I'll update after I fix it.

**Comment by MoSadie** [comment]
Ok. Uploaded v1.2.2 to Curse as of now. Please reopen the issue if it happens again.
